name: CI
run-name: ${{ github.actor }} CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: bitnami/python:3.10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install
        run: |
          export PATH=$PATH:/github/home/.local/bin
          python3 -m pip install --user pipx
          pipx install pdm
          pdm export -d -o requirements.txt --without-hashes
          pip3 install -r requirements.txt

      - name: pytest
        run: |
          export PYTHONPATH=(pwd)
          cd tests
          pytest -sx
