name: CI
run-name: ${{ github.actor }} CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: bitnami/python:3.10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install
        run: pdm install

      - run: cd tests && pdm run pytest -sx
